### ISSUE TITLE
기능명세

### ISSUE THREAD

**Issue by changhwa** [codechobostudy/code-chobo-study#1]
프로토타이핑 할 기능명세를 진행한다.

**Comment by changhwa** [comment]
제가 생각할때 필요한 기능 몇가지만 고민해봤습니다.
1. 질문 - 답변 개편  
   stackoverflow 의 형태를 따라가는게 어떨까 합니다.  
   질문 답변에 최적화 상태고 저희 개발자들도 대부분 익숙하다보니 편한 것 같습니다.  
   다만 답변자의 프로필을 좀더 명확하게 보여줄 방안은 없을지에 대한 고민과  
   질문과 답변 등에서 다른 질문과 답변을 좀 더 쉽게 인용할 수 있는 방안은 고민해보면  
   좋을 것 같습니다.  
   물론 히스토리 관리도 되어야하구요 (질문삭제시에 대한 히스토리 유지 필요)  
2. 스터디 모집 및 관리 기능  
   예전에 봄싹 스터디 홈페이지에서 봤던 기능인데요 스터디를 모집받고 관리하는 페이지 였는데
   상당히 인상 깊었습니다.  
   저희 코초스는 스터디 모집등이 활발한 편인데 이런 부분을 좀 더 코초스 자체에서  
   제공해줌으로써 편리하고 유익하게 공유되면 좋을 것 같습니다.  
3. 질문 - 답변 퀄리티 개선  
   중복 질문은 최대한 없애는 방안으로 가야할텐데 질문자가 질문을 작성하고 나면  
   과거 비슷한 질문이 있었는지 추천해주고 없을 경우에만 등록하도록 유도하면 어떨지  
   또한 코드가 스크린샷이거나 질문의 질이 너무 낮거나 하는 경우 싫어요 등을 활용해  
   집단지성에 의해 자연스레 개선되도록하고  
   권한을 갖는 운영진들이 직접 질문을 수정할 수 도 있도록 합니다.  
4. 답변자에 대한 레벨 체계  
   답변 단 횟수 , 해당 답변에 대한 추천도 등을 집계하여 레벨화 하면 좋겠습니다.  
5. 마크업  
   질문-답변이나 기타 커뮤니티 게시판 등에서 마크다운, 일반에디터 둘다 지원되도록 하고 에디터는 뭐를 쓸지 고민해볼 필요가 있습니다.
6. 데이터 마이닝  
   검색시에도 단순한 LIKE 검색이 아닌 추천검색, 연관검색등을 통해 좀 더 많은 부분에서 유저에게 편안함이 제공되면 좋겠습니다.
7. 유저권한의 세분화  
   단순히 최고운영자 - 사용자 단계가 아닌 세분화하여 권한 메트릭스 등을 사용하여
   운영자의 업무를 최소화하는 방향으로 나아가면 어떨까요
8. 관리자 페이지  
   여러 통계 (예를 들자면 방문자 수, 유입키워드 , 주요 검색 순위, 등등) 등을 손쉽게 제공하여 운영면에서 많은 도움이 되도록 제공
9. 글 연재 기능  
   좀 더 쉽게 글을 연재하고 보는 맛이 있도록 구성하면 좋을 것 같습니다.  
   제가 해당 프로젝트의 영감을 받은 사이트 입니다. http://we.weirdmeetup.com/  
   이런 형태로 뭔가 읽는 맛이 나도록 보여주면 좋겠습니다.

**Comment by writer0713** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

writer0713@naver.com 님께 보내신 메일 <Re: [code-chobo-study] 기능명세 (#1)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by scarfunk** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

scarfunk@naver.com 님께 보내신 메일 <[code-chobo-study] 기능명세 (#1)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by scarfunk** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

scarfunk@naver.com 님께 보내신 메일 <Re: [code-chobo-study] 기능명세 (#1)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by writer0713** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

writer0713@naver.com 님께 보내신 메일 <[code-chobo-study] 기능명세 (#1)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by changhwa** [comment]
저는 카테고리는 그다지 유용한 방법이 아니라고 생각합니다.
태그, 문서내용, 삽입문서 등을 통해 자연스럽게 그래프 자료구조처럼
보여지는게 맞다고 생각합니다. (언제든 의견주세요!)

다만 저희 코초스가 커버하는 영역이
일반커뮤니티 (맘대로쓰세요 - 고민상담게시판 - 잡담게시판 - 유머 등)
질문답변형 개발커뮤니티 (자바QnA 등)
스터디커뮤니티 ( 각 기수 스터디 게시판)
강의커뮤니티 ( 각 강좌 게시판)
등등 커뮤니티 성격이 전혀 다른 부분들이 섞여있는데

이것만 메뉴 ( 또는 카테고리 ) 로 분류하고 그 안은 카테고리보다는
태그, 문서내용, 삽입문서 등을 활용하여 자연스럽게 접근할 수 있도록 하면 어떨까 싶습니다.

**Comment by changhwa** [comment]
로그인이 카페 회원으로 뿐만 아니라 페이스북, 트위터, 구글, 깃허브 등 잘 지원했으면 좋겠습니다.
로그인인 관련 공통 인터페이스를 정의하고 로그인서비스는 각 인터페이스를 구현하도록 하고..
외부로그인시 자연스럽게 내부에서는 내부회원으로 되도록..

**Comment by castello** [comment]
카테고리라는 것은 고정적인 것이니까요. 태그를 이용해서 얼마든지 카테고리를 재구성할 수 있습니다. 태그를 시스템적으로 생성해서 카테고리를 구성하면 되니까요. 일단 고정적인 카테고리는 신경쓰지 않아도 될 것 같습니다.

**Comment by changhwa** [comment]
회원 - 3분 배정완료
질문답변 -  미정 
스터디 모집 & 관리 - 2분 배정완료 (
마크업 - 1분 배정완료
일반게시판 - 1분 배정완료

**Comment by scarfunk** [comment]
서비스별 할당인원 이름을 알려주세요 이슈 assign 할려는데 누군지 기억이 안나네요 ㅠ

**Comment by changhwa** [comment]
마크업하시는 분은 질문답변으로 재배정
질문답변에 저도 같이 참여.

@scarfunk 저도 깃허브 아이디는 햇갈리는 군요 월요일에 정리해보겠습니다.^^
