### ISSUE TITLE
스터디 관리 (1번)

### ISSUE THREAD

**Issue by changhwa** [codechobostudy/code-chobo-study#2]
#### 스터디 관리 기능을 개발한다 ( ver. 1)
- [x] 스터디를 개설/수정/삭제
- [ ] 스터디 모집글 등록/수정/삭제
- [ ] 스터디 참여를 신청한다.
- [ ] 스터디 참여를 취소한다.
- [ ] 스터디 참가자 현황을 본다.
- [ ] 스터디 출석부를 만든다.

**Comment by scarfunk** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

scarfunk@naver.com 님께 보내신 메일 <[code-chobo-study] 스터디 관리 ( (#2)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by writer0713** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

writer0713@naver.com 님께 보내신 메일 <[code-chobo-study] 스터디 관리 ( (#2)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by writer0713** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

writer0713@naver.com 님께 보내신 메일 <Re: [code-chobo-study] 스터디 관리 ( (#2)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by scarfunk** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

scarfunk@naver.com 님께 보내신 메일 <Re: [code-chobo-study] 스터디 관리 ( (#2)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by writer0713** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

writer0713@naver.com 님께 보내신 메일 <Re: [code-chobo-study] 스터디 관리 (1번) (#2)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by scarfunk** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

scarfunk@naver.com 님께 보내신 메일 <Re: [code-chobo-study] 스터디 관리 (1번) (#2)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by changhwa** [comment]
해당 이슈는 담당자 및 이슈 변경됨
