### ISSUE TITLE
일반 게시글이나 질답에서 지켜보기 기능

### ISSUE THREAD

**Issue by changhwa** [codechobostudy/code-chobo-study#5]
일반 게시글이나 질문 답변에서 카페의 경우 제가 댓글을 달거나 게시자인 경우에만 알림이 옵니다.
원할경우 깃허브에 watch 처럼 설정하면 해당 게시글, 질답이 업데이트 될 시 알람이 있음 어떨까요.

**Comment by writer0713** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

writer0713@naver.com 님께 보내신 메일 <[code-chobo-study] 일반 게시글이나 질답에서 지켜보기 기능 (#5)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by scarfunk** [comment]
네 알람 기능은 매우 필요하다고 생각합니다
naver 도 메인에서까지도 댓글알람이 되지요
자주가는 okky 도 개편되며 알람시스템이 편리하게 바뀐 느낌입니다.
회원정보가 표기되는 navbar 등에서 보여지게 구현되면 좋겠네요

**Comment by writer0713** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

writer0713@naver.com 님께 보내신 메일 <Re: [code-chobo-study] 일반 게시글이나 질답에서 지켜보기 기능 (#5)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by changhwa** [comment]
@scarfunk  아예 해당 backlog를 발전시켜서 알람센터로 갔으면 합니다.
이런 알람 뿐만 아니라 페이스북 알람 처럼요..^^
이건 프로젝트로 건의 합니다. 

@jinhyun  만약 특별히 정해놓으신거 없다면 해당 프로젝트 추천합니다.
이유
1. 스프링 웹소켓을 통한 기본 웹소켓 개념 확립
2. 알람센터도 DB가 필요하므로 JPA 기본개념에 좋을듯합니다.
3. 다른 서비스에서 어떻게하면 편하게 알람센터를 사용할 수있을지 고민해볼 수 있습니다.
(URL 열어주고 사용하게 하던지 알람을 사용할 서비스의 경우 특정 인터페이스를 구현한다던지 등)

**Comment by changhwa** [comment]
해당 이슈는 알람센터라는 이름으로 진행하기로 했습니다..
@jinhyun 
기능에 대한 정리가 끝나면 새로운 이슈로 생성해서 feature, ing  라벨을 붙여주세요.

**Comment by jinhyun** [comment]
네 알겠습니다~
